spring:
  application:
    name: onboarding-service
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  liquibase:
    change-log: db/changelog/changelog.yaml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false


logging:
  level:
    liquibase: DEBUG

service:
  accounting:
    url: ${ACCOUNTING_URL}
  security:
    url: ${SECURITY_URL}


